Update the scripts and the readme file

diff --git a/copy-template b/copy-template
--- a/copy-template
+++ b/copy-template
@@ -1,184 +1,212 @@
 #!/bin/sh
 # -*- sh -*-
-# vim: set syntax=sh
+# vim: syntax=sh
 # code: language=shellscript
 
-# Copyright (c) 2022 Michael Federczuk
+# Copyright (c) 2023 Michael Federczuk
 # SPDX-License-Identifier: MPL-2.0 AND Apache-2.0
+
+#region preamble
+
+case "$-" in
+	(*'i'*)
+		\command printf 'script was called interactively\n' >&2
+		return 124
+		;;
+esac
 
 set -o errexit
 set -o nounset
 
-argv0() {
-	if [ "$0" = "$(realpath -s -- "$0")" ]; then
-		printf '%s' "$(basename -- "$0")"
-	else
-		printf '%s' "$0"
-	fi
-}
+# enabling POSIX-compliant behavior for GNU programs
+export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes
 
-log() {
-	case $# in
-		(0)
-			echo 'log: missing argument: <message>' >&2
-			exit 123
-			;;
-		(1) ;;
-		(*)
-			echo "log: too many arguments: $(($# - 1))" >&2
-			exit 123
-			;;
-	esac
-
-	printf -- '%s\n' "$1" >&2
-}
-errlog() {
-	case $# in
-		(0)
-			echo 'error: missing argument: <message>' >&2
-			exit 123
-			;;
-		(1) ;;
-		(*)
-			echo "error: too many arguments: $(($# - 1))" >&2
-			exit 123
-			;;
-	esac
-
-	log "$(argv0): $1"
-}
-
-root_dir_path="$(realpath --relative-to=. -- "$0")"
-root_dir_path="$(dirname -- "$root_dir_path")"
-readonly root_dir_path
-
-templates_location_dir_path="$(realpath --relative-base=. -ms -- "$root_dir_path/templates")"
-readonly templates_location_dir_path
-
-if [ ! -e "$templates_location_dir_path" ]; then
-	errlog "$templates_location_dir_path: no such directory"
-	exit 24
+if [ "${0#/}" = "$0" ]; then
+	argv0="$0"
+else
+	argv0="$(basename -- "$0" && printf x)"
+	argv0="${argv0%"$(printf '\nx')"}"
 fi
-if [ ! -d "$templates_location_dir_path" ]; then
-	errlog "$templates_location_dir_path: not a directory"
-	exit 26
-fi
+readonly argv0
 
-# region args
+#endregion
+
+#region args
 
 print_usage() {
-	log "usage: $(argv0) (--list | <source> <target>)"
+	printf 'usage: %s <template_source> <target>\n' "$argv0"
+	printf '   or: %s --list\n' "$argv0"
 }
 
-if [ "${1-}" = '--help' ]; then
-	print_usage
-	exit
-fi
+for arg in "$@"; do
+	if [ "$arg" = '--help' ]; then
+		print_usage
+		exit
+	fi
+done; unset -v arg
 
-list_templates=false
+list_standard_templates=false
 
 case $# in
 	(0)
-		errlog 'missing arguments: (--list | <source> <target>)'
-		print_usage
+		{
+			printf '%s: missing arguments: (--list | <template_source> <target>)\n' "$argv0"
+			print_usage
+		} >&2
 		exit 3
 		;;
 	(1)
-		case "$1" in
-			('--list')
-				list_templates=true
-				;;
-			(*)
-				errlog 'missing argument: <target>'
+		if [ "$1" != '--list' ]; then
+			{
+				printf '%s: missing argument: <target>\n' "$argv0"
 				print_usage
-				exit 3
-				;;
-		esac
+			} >&2
+			exit 3
+		fi
+
+		list_standard_templates=true
 		;;
 	(2)
-		case "$1" in
-			('--list')
-				errlog "too many arguments: $(($# - 1))"
+		if [ "$1" = '--list' ]; then
+			{
+				printf '%s: too many arguments: %i\n' "$argv0" $(($# - 1))
 				print_usage
-				exit 4
-				;;
-			(*)
-				# nothing since correct usage
-				;;
-		esac
+			} >&2
+			exit 4
+		fi
+
+		if [ -z "$1" ]; then
+			{
+				printf '%s: argument 1: must not be empty\n' "$argv0"
+				print_usage
+			} >&2
+			exit 9
+		fi
+		if [ -z "$2" ]; then
+			{
+				printf '%s: argument 2: must not be empty\n' "$argv0"
+				print_usage
+			} >&2
+			exit 9
+		fi
+
+		template_source="$1"
+		target_file_pathname="$2"
 		;;
 	(*)
-		case "$1" in
-			('--list') expected_argc=1 ;;
-			(*)        expected_argc=2 ;;
-		esac
+		if [ "$1" = '--list' ]; then
+			expected_argc=1
+		else
+			expected_argc=2
+		fi
+		readonly expected_argc
 
-		errlog "too many arguments: $(($# - expected_argc))"
-		print_usage
+		{
+			printf '%s: too many arguments: %i\n' "$argv0" $(($# - expected_argc))
+			print_usage
+		} >&2
 		exit 4
 		;;
 esac
 
-if $list_templates; then
-	printf '%s\n' "$templates_location_dir_path/"*'.tex' | sed -E s%'(.*/)?([^/]+)\.tex$'%'\2'%
-	exit
-fi
+readonly list_standard_templates \
+         template_source target_file_pathname
 
-source="$1"
-if [ -z "$source" ]; then
-	errlog 'argument 1: must not be empty'
-	exit 9
-fi
-source="$(realpath -ms --relative-base=. -- "$source")"
+unset -f print_usage
 
-target="$2"
-if [ -z "$target" ]; then
-	errlog 'argument 2: must not be empty'
-	exit 9
-fi
-target="$(realpath -ms --relative-base=. -- "$target")"
+#endregion
 
-if [ ! -e "$source" ]; then
-	fallback=''
+print_xdg_data_home_pathname() {
+	# <https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html>
 
-	if ! printf '%s' "$source" | grep -Eq '/'; then
-		tmp="$templates_location_dir_path/$source.tex"
-
-		if [ -f "$tmp" ]; then
-			fallback="$tmp"
-		fi
-
-		unset -v tmp
+	if [ "${XDG_DATA_HOME-#"/"}" != "$XDG_DATA_HOME" ]; then
+		# only absolute pathnames are valid
+		printf '%s' "$XDG_DATA_HOME"
+		return
 	fi
 
-	if [ -z "$fallback" ]; then
-		errlog "$1: no such file"
+	if [ -z "${HOME-}" ]; then
+		printf '%s: the environment variable HOME must not be unset or empty\n' "$argv0" >&2
+		return 48
+	fi
+
+	if [ "${HOME#"/"}" = "$HOME" ]; then
+		printf '%s: the environment variable HOME must be absolute\n' "$argv0" >&2
+		return 49
+	fi
+
+	printf '%s/.local/share' "$HOME"
+}
+
+print_valid_standard_templates_dir_pathname() {
+	set -- "$(print_xdg_data_home_pathname && printf x)"
+	set -- "${1%"x"}"
+	set -- "$1/latex-templates/templates"
+
+	if [ -e "$1" ] && [ ! -d "$1" ]; then
+		printf '%s: %s: not a directory\n' "$argv0" "$1" >&2
 		exit 24
 	fi
 
-	source="$fallback"
-	unset -v fallback
+	printf '%s' "$1"
+}
+
+
+if $list_standard_templates; then
+	standard_templates_dir_pathname="$(print_valid_standard_templates_dir_pathname)"
+	readonly standard_templates_dir_pathname
+
+	printf '%s:\n' "$standard_templates_dir_pathname"
+
+	if [ ! -e "$standard_templates_dir_pathname" ]; then
+		exit
+	fi
+
+	(
+		cd "$standard_templates_dir_pathname"
+		printf '%s\n' ./*.tex | sed -e s%'^\./\(..*\)\.tex$'%'\1'%
+	)
+	exit
 fi
-if [ ! -f "$source" ]; then
-	errlog "$1: not a regular file"
+
+
+#region checking source & target
+
+if printf '%s' "$template_source" | grep -Eq '/'; then
+	template_file_pathname="$template_source"
+else
+	standard_templates_dir_pathname="$(print_valid_standard_templates_dir_pathname)"
+
+	template_file_pathname="$standard_templates_dir_pathname/$template_source.tex"
+
+	unset -v standard_templates_dir_pathname
+fi
+readonly template_file_pathname
+
+if [ ! -e "$template_file_pathname" ]; then
+	printf '%s: %s: no such file\n' "$argv0" "$template_file_pathname" >&2
+	exit 24
+fi
+if [ ! -f "$template_file_pathname" ]; then
+	printf '%s: %s: not a regular file\n' "$argv0" "$template_file_pathname"
+	exit 24
+fi
+
+
+if [ -e "$target_file_pathname" ] && [ ! -f "$target_file_pathname" ]; then
+	printf '%s: %s: not a regular file\n' "$argv0" "$target_file_pathname" >&2
 	exit 26
 fi
 
-if [ -e "$target" ] && [ ! -f "$target" ]; then
-	errlog "$2: not a regular file"
-	exit 26
-fi
+#endregion
 
-readonly source target
+#region copying template
 
-# endregion
-
-today="$(date +%s)"
-readonly today
-
-day="$(date -d"@$today" +%d)"
-month="$(date -d"@$today" +%m)"
-year="$(date -d"@$today" +%Y)"
+day="$(date +%d)"
+month="$(date +%m)"
+year="$(date +%Y)"
 readonly day month year
 
-sed -E /'^[[:space:]]*%%'/d\;s/'[[:space:]]*%%.*$'//\;s/'<DAY>'/"$day"/g\;s/'<MONTH>'/"$month"/g\;s/'<YEAR>'/"$year"/g "$source" > "$target"
+sed /'^[[:space:]]*%%'/d\;s/'[[:space:]]*%%.*$'//\;s/'<DAY>'/"$day"/g\;s/'<MONTH>'/"$month"/g\;s/'<YEAR>'/"$year"/g "$template_file_pathname" > "$target_file_pathname"
+
+#endregion
